#!/usr/bin/env bash
# Regenerate super_interrupts.lua from keybinds.lua.
#
# Run this after adding or removing any SUPER binding. The two files must
# agree, and the failure when they do not is subtle: the launcher opens on
# a combination you used for something else.
set -euo pipefail
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

{
cat <<'HEADER'
-- Super-tap interrupts. GENERATED by gen-super-interrupts.sh — do not edit.
--
-- The launcher opens on RELEASE of a bare Super tap. While Super is held,
-- pressing anything else has to cancel that pending open, or Super+Shift+S
-- takes a screenshot AND opens the launcher when Super comes up.
--
-- Up to Hyprland 0.55 a single `binditn = SUPER, catchall` did this for every
-- key at once. On 0.56 catchall is submap-only, so every SUPER combination
-- instead gets a second, `transparent` bind firing the interrupt. Transparent
-- means Hyprland keeps scanning after it, so the real bind on the same keys
-- still runs.
HEADER
grep -oE '^hl\.bind\("[^"]*SUPER[^"]*"' "$dir/keybinds.lua" \
    | sed 's/^hl\.bind("//; s/"$//' \
    | grep -vE '^(SUPER \+ )?Super_[LR]$' \
    | grep -vE 'Super_[LR]' \
    | sort -u \
    | while IFS= read -r combo; do
        printf 'hl.bind("%s", hl.dsp.global("quickshell:superComboInterrupt"), { transparent = true })\n' "$combo"
      done

# The workspace binds are built in a Lua loop (`"SUPER + " .. key`), so the
# grep above cannot see them. They still need interrupts, or Super+4 opens
# the launcher on top of workspace 4.
for n in 1 2 3 4 5 6 7 8 9 0; do
    printf 'hl.bind("SUPER + %s", hl.dsp.global("quickshell:superComboInterrupt"), { transparent = true })\n' "$n"
    printf 'hl.bind("SUPER + SHIFT + %s", hl.dsp.global("quickshell:superComboInterrupt"), { transparent = true })\n' "$n"
done
} > "$dir/super_interrupts.lua"

printf 'wrote %s (%d interrupts)\n' "$dir/super_interrupts.lua" \
    "$(grep -c '^hl.bind' "$dir/super_interrupts.lua")"
