#!/usr/bin/env bash
# HUD 10-band PipeWire equalizer — install / live control.
#
# Builds a native filter-chain virtual sink ("Equalizer") with 10 biquad
# bands (31 Hz – 16 kHz). Band gains are changed live via `pw-cli set-param`
# — no PipeWire restart needed once installed.
#
# Usage:
#   hud-equalizer.sh install         write the conf + restart PipeWire
#   hud-equalizer.sh remove          delete the conf + restart PipeWire
#   hud-equalizer.sh status          → installed=<yes|no> id=<nodeid|->
#   hud-equalizer.sh apply ID g0..g9 set the 10 band gains (dB) on node ID
#   hud-equalizer.sh enable  ID      route system audio through the EQ sink
#   hud-equalizer.sh disable         route audio back to the previous sink
set -u

CONF_DIR="$HOME/.config/pipewire/pipewire.conf.d"
CONF="$CONF_DIR/99-hud-equalizer.conf"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/quickshell"
PREV_SINK="$STATE_DIR/hud-eq-prev-sink"
SINK_NAME="effect_input.hud-eq"

write_conf() {
    mkdir -p "$CONF_DIR"
    cat > "$CONF" <<'EOF'
# Generated by hud-equalizer.sh — 10-band graphic equalizer sink.
context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "HUD Equalizer"
      media.name       = "HUD Equalizer"
      filter.graph = {
        nodes = [
          { type = builtin name = hudeq0 label = bq_lowshelf  control = { "Freq" = 31    "Q" = 1.0 "Gain" = 0.0 } }
          { type = builtin name = hudeq1 label = bq_peaking   control = { "Freq" = 63    "Q" = 1.4 "Gain" = 0.0 } }
          { type = builtin name = hudeq2 label = bq_peaking   control = { "Freq" = 125   "Q" = 1.4 "Gain" = 0.0 } }
          { type = builtin name = hudeq3 label = bq_peaking   control = { "Freq" = 250   "Q" = 1.4 "Gain" = 0.0 } }
          { type = builtin name = hudeq4 label = bq_peaking   control = { "Freq" = 500   "Q" = 1.4 "Gain" = 0.0 } }
          { type = builtin name = hudeq5 label = bq_peaking   control = { "Freq" = 1000  "Q" = 1.4 "Gain" = 0.0 } }
          { type = builtin name = hudeq6 label = bq_peaking   control = { "Freq" = 2000  "Q" = 1.4 "Gain" = 0.0 } }
          { type = builtin name = hudeq7 label = bq_peaking   control = { "Freq" = 4000  "Q" = 1.4 "Gain" = 0.0 } }
          { type = builtin name = hudeq8 label = bq_peaking   control = { "Freq" = 8000  "Q" = 1.4 "Gain" = 0.0 } }
          { type = builtin name = hudeq9 label = bq_highshelf control = { "Freq" = 16000 "Q" = 1.0 "Gain" = 0.0 } }
        ]
        links = [
          { output = "hudeq0:Out" input = "hudeq1:In" }
          { output = "hudeq1:Out" input = "hudeq2:In" }
          { output = "hudeq2:Out" input = "hudeq3:In" }
          { output = "hudeq3:Out" input = "hudeq4:In" }
          { output = "hudeq4:Out" input = "hudeq5:In" }
          { output = "hudeq5:Out" input = "hudeq6:In" }
          { output = "hudeq6:Out" input = "hudeq7:In" }
          { output = "hudeq7:Out" input = "hudeq8:In" }
          { output = "hudeq8:Out" input = "hudeq9:In" }
        ]
      }
      audio.channels = 2
      audio.position = [ FL FR ]
      capture.props = {
        node.name        = "effect_input.hud-eq"
        node.description = "Equalizer"
        media.class      = Audio/Sink
      }
      playback.props = {
        node.name    = "effect_output.hud-eq"
        node.passive = true
      }
    }
  }
]
EOF
}

restart_pw() {
    systemctl --user restart pipewire pipewire-pulse wireplumber 2>/dev/null || true
}

# Node id of the EQ filter-chain sink (empty if not present yet).
eq_id() {
    pw-dump 2>/dev/null | jq -r --arg n "$SINK_NAME" \
        '.[] | select(.type=="PipeWire:Interface:Node"
                       and .info.props["node.name"]==$n) | .id' | head -1
}

# Node id of the filter-chain OUTPUT node (used for the headroom volume).
out_id() {
    pw-dump 2>/dev/null | jq -r \
        '.[] | select(.type=="PipeWire:Interface:Node"
                       and .info.props["node.name"]=="effect_output.hud-eq") | .id' | head -1
}

case "${1:-status}" in
  install)
    write_conf
    restart_pw
    echo "installed"
    ;;

  remove)
    rm -f "$CONF"
    restart_pw
    echo "removed"
    ;;

  status)
    [ -f "$CONF" ] && inst=yes || inst=no
    id="$(eq_id)"
    oid="$(out_id)"
    echo "installed=$inst id=${id:--} out=${oid:--}"
    ;;

  apply)   # apply SINK_ID OUT_ID g0 g1 ... g9
    id="${2:-}"
    oid="${3:-}"
    # The filter-graph controls AND the headroom volume both live on the
    # filter-chain OUTPUT node — not the sink the user routes audio into.
    if [ -z "$oid" ] || [ "$oid" = "-" ]; then oid="$id"; fi
    [ -z "$oid" ] && { echo "no-id"; exit 1; }
    shift 3
    gains=()
    for i in 0 1 2 3 4 5 6 7 8 9; do
        gains+=("${1:-0}"); shift 2>/dev/null || true
    done
    params=""
    for i in 0 1 2 3 4 5 6 7 8 9; do
        params="$params \"hudeq$i:Gain\" ${gains[$i]}"
    done
    pw-cli set-param "$oid" Props "{ params = [ $params ] }" >/dev/null 2>&1
    # Auto headroom: attenuate by the largest boost so a boosted band can't
    # push past 0 dBFS and clip (distortion).
    mult="$(awk -v g="${gains[*]}" 'BEGIN{
        n = split(g, a, " "); mx = 0;
        for (i = 1; i <= n; i++) if (a[i] + 0 > mx) mx = a[i] + 0;
        printf "%.4f", 10 ^ (-mx / 20) }')"
    wpctl set-volume "$oid" "$mult" 2>/dev/null
    echo "applied"
    ;;

  enable)  # enable ID
    id="${2:-}"
    [ -z "$id" ] && { echo "no-id"; exit 1; }
    mkdir -p "$STATE_DIR"
    cur="$(wpctl inspect @DEFAULT_AUDIO_SINK@ 2>/dev/null \
           | sed -n 's/.*node\.name = "\([^"]*\)".*/\1/p' | head -1)"
    [ -n "$cur" ] && [ "$cur" != "$SINK_NAME" ] && printf '%s' "$cur" > "$PREV_SINK"
    wpctl set-default "$id" 2>/dev/null && echo "enabled" || echo "enable-failed"
    ;;

  disable)
    prev="$(cat "$PREV_SINK" 2>/dev/null)"
    pid=""
    [ -n "$prev" ] && pid="$(pw-dump 2>/dev/null | jq -r --arg n "$prev" \
        '.[] | select(.type=="PipeWire:Interface:Node"
                       and .info.props["node.name"]==$n) | .id' | head -1)"
    # Fall back to any hardware sink if the saved one is gone.
    [ -z "$pid" ] && pid="$(pw-dump 2>/dev/null | jq -r \
        '.[] | select(.info.props["media.class"]=="Audio/Sink"
                       and (.info.props["node.name"]|test("hud-eq")|not)
                       and .info.props["device.id"]) | .id' | head -1)"
    [ -n "$pid" ] && wpctl set-default "$pid" 2>/dev/null
    echo "disabled"
    ;;

  *)
    echo "usage: hud-equalizer.sh {install|remove|status|apply|enable|disable}"
    exit 1
    ;;
esac
